spring:
  datasource:
    url: jdbc:h2:mem:planus-db
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  server:
    port: 8080
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
