name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"

      - name: Create application.yml
        run: |
          echo "${{ secrets.BACKEND_APP_YML }}" > ./src/main/resources/application.yml
          echo "${{ secrets.BACKEND_APP_PROD_YML }}" > ./src/main/resources/application-prod.yml

      - name: chmod gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/planus-prod"
          strip_components: 2

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH and restart Spring Boot app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd /home/ubuntu/planus-prod
            pkill -f 'java -jar' || true
            nohup java -jar *.jar > nohup.out 2>nohup.err < /dev/null &
            sleep 30
            exit 0
